[package]
name = "rbe"
version = "0.1.29"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
documentation = "https://docs.rs/rbe"
homepage.workspace = true
repository.workspace = true

[dependencies]
thiserror = "1"
hashbag = { version = "0.1.11"}
serde = "1.0"
serde_derive = "1.0"
serde_json = { workspace = true }
serde_yml = "0.0.12"
itertools = "0.13"
indexmap = { version = "2"}
tracing = { workspace = true }

[dev-dependencies]
indoc = "2"
