[package]
name = "sparql_service"
version = "0.1.60"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
documentation = "https://docs.rs/sparql_service"
homepage.workspace = true
repository.workspace = true

[features]
rdf-star = [
    "srdf/rdf-star",
    "oxrdf/rdf-star",
    "oxrdfio/rdf-star",
    "sparesults/rdf-star",
]

[dependencies]
const_format = "0.2"
thiserror = "1"
lazy_static = "1"
serde.workspace = true
serde_yaml_ng = "0.10"
itertools = "0.13"
iri_s.workspace = true
prefixmap.workspace = true
srdf = { workspace = true, features = [ "rdf-star"] }
oxsdatatypes = "0.2.0-alpha.2"
oxigraph = { version = "0.4.0-rc.2", default-features = false }
oxrdf = { workspace = true, features = [ "oxsdatatypes", "rdf-star"] }
oxrdfio = { version = "0.1.0-alpha.5", features = [ "rdf-star" ]}
colored.workspace = true
sparesults = { version = "0.2.0-alpha.5", features = [ "rdf-star" ] }
rust_decimal = "1.32"
