[package]
name = "sparql_service"
version = "0.1.15"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
documentation = "https://docs.rs/sparql_service"
homepage.workspace = true
repository.workspace = true

[dependencies]
thiserror = "1"
hashbag = { version = "0.1.11"}
serde = "1.0"
serde_derive = "1.0"
serde_json = { workspace = true }
serde_yaml = "0.9"
itertools = "0.13"
indexmap = { version = "2"}
iri_s = { workspace = true }
tracing = { workspace = true }

