[package]
name = "rudof_cli"
version = "0.1.29"
authors.workspace = true
description.workspace = true
documentation = "https://rudof-project.github.io/rudof"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
path = "src/main.rs"
name = "rudof"

[dependencies]
shex_ast = { workspace = true }
shex_validation = { workspace = true }
srdf = { workspace = true, features = ["rdf-star"] }
prefixmap = { workspace = true }
iri_s = { workspace = true }
shapemap = { workspace = true }
shex_compact = { workspace = true }
shacl_ast = { workspace = true, features = ["rdf-star"] }
dctap = { workspace = true }
shapes_converter = { workspace = true, features = ["rdf-star"] }
shacl_validation = { workspace = true }
sparql_service = { workspace = true }
 
serde = "1.0"
serde_derive = "1.0"
serde_json = { workspace = true }
anyhow = "1.0"
thiserror = "1.0"
void = "1"
clap = { workspace = true }
oxrdf = { workspace = true }
oxiri = "0.2.3-alpha.1"
regex = "^1.10"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
supports-color = { workspace = true }
either = "1.13"
reqwest = { version = "0.12" }
