[package]
name = "rbe_testsuite"
version = "0.1.29"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/rbe_testsuite"
edition.workspace = true
license.workspace = true

[dependencies]
rbe = { workspace = true }
serde.workspace = true
serde_yaml_ng = "0.10"
anyhow = "1.0.27"
tracing = { workspace = true }

[dev-dependencies]
indoc = "2"
