[package]
name = "iri_s"
version = "0.1.58"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/iri_s"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
rdf-star = [ "oxrdf/rdf-star" ]

[dependencies]
lazy_static = "1"
oxrdf = { version = "0.2.0-alpha.5" }
oxiri = "0.2.3-alpha.1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = "1.0"
serde_derive = "1.0"
thiserror = "1.0.0"
url = { workspace = true }
