[package]
name = "shex_testsuite"
version = "0.1.58"
authors.workspace = true
description.workspace = true
documentation = "https://docs.rs/shex_testsuite"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
iri_s = { workspace = true }
prefixmap = { workspace = true }
srdf = { workspace = true }
shex_ast = { workspace = true }
shex_compact = { workspace = true }
shex_validation = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
serde_yml = "0.0.12"
anyhow = "1.0"
thiserror = "1.0"
void = "1"
clap = { workspace = true }
oxrdf = "0.2.0-alpha.2"
oxiri = "0.2.3-alpha.1"
url = { workspace = true }
tracing = { workspace = true }
