[book]
authors = ["Jose Emilio Labra Gayo", "Ángel Iglesias Préstamo"]
language = "en"
multilingual = false
src = "src"
title = "rudof"
site-url = "/docs/"

[output.html.print]
enable = false

[output.html]
no-section-label = true
preferred-dark-theme = "dark"
additional-css = ["theme/pagetoc.css", "theme/highlight.css"]
additional-js = ["theme/pagetoc.js", "theme/plugins.js"]